### ISSUE TITLE
Assumed ball height not being sent in ball plugin

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboCup-SSL/ssl-vision#160]
The assumed height of the ball is important part of the calculation/ for end-users to be able to replicate calculations, but currently is not being sent with the protobuf message.

**Comment by g3force** [comment]
What do you need the value for? 

There are different ball heights:
1. The actual ball height if the ball is flying (not available in ssl-vision)
1. The ball z-value based on the size of the ball (21.5mm)
1. The ball z-value that is used for conversions from image to field coordinates (30mm, manually optimized many years ago, I guess because the ball is round?)

Without any additional documentation, I would expect the first one in the protobuf message.

**Comment by rolfvdhulst** [comment]
I actually mean option 3), the 30 mm here; in general the only reason I can see why you would send the camera parameters to the end user is so they can recompute the positions if they desire to do so (and e.g. find the 3d rays on which the ball should be). This is also the main purpose for sending the robot height.

**Comment by g3force** [comment]
I rather see option 3 as part of the geometry, not the detection, because it is constant. My impression is though, that this is an internal value, optimized for the ssl-vision code and should not be exposed.

I can definitely see, why one need the robot height, but what exactly do you need this 30mm value for? :thinking:

**Comment by rolfvdhulst** [comment]
I don't mind nothing being sent, but why is the field then still a part of the protobuf message?

**Comment by g3force** [comment]
It was added ten years ago, but I do not think it was ever used. It could probably be deleted.

**Comment by g3force** [comment]
I'll close this issue and the related PR then.
