### ISSUE TITLE
Ball near robot filters filters away chipped balls

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboCup-SSL/ssl-vision#178]
This is not really a trivial feature/problem. In good vision conditions, it may be more advisable to even simply disable the near-robot filter.
Needs further investigation/data collection to check if indeed the near robot filter is to blame or if e.g. vision blur can be blamed, but it's very likely that the near robot filter filters away balls that are exactly in line with a robot.

**Comment by g3force** [comment]
Note that a chipped ball only moves in a straight line across the image, when it moves along an image axis. Nearer to the edges, it rather moves in a curve.
Also note, that due to the height, the ball blob gets bigger. If the size exceeds the maximum blob size for the ball, it won't be detected as well.
I'm actually not sure if it is really an issues. It would only be one sample in many, right?

Two suggestions:
1. Check the raw ball data in the game logs. You should roughly see if a sample should be above a robot and if it actually is.
2. Check SSL_DetectionBall#area in the detection messages. It should give the area of the ball blob. The default for "Max Area (sq-pixels)" is 1000.
