### ISSUE TITLE
detection of new fields (Division A and B)

### ISSUE THREAD

**Issue by mahi97** [RoboCup-SSL/ssl-vision#86]
should SSL-vision change its geometry message and field detection to compatible with the current rules?

**Comment by g3force** [comment]
There is no need to change any message format, but the legacy geometry message is not sufficient anymore, because it includes the radius of the penalty area.

See also #87.

I plan to simplify the configuration of field coordinates, so that it will be easier to update them based on field size and number of cameras. Stay tuned.

**Comment by g3force** [comment]
calibration simplified and also updated for a distributed 8 camera setup: #88
